deploy_admin_console: true
deploy_olm: true

olm_version: "0.7.1"
admin_console_image: "quay.io/openshift/origin-console:latest"

# The upstream OLM repo that will be cloned and used for deployment
olm_repo: "https://github.com/operator-framework/operator-lifecycle-manager.git"
olm_repo_dest: /tmp/olm
olm_manifest_type: okd
