deploy_admin_console: true
deploy_olm: true

olm_version: "0.7.1"
admin_console_image: "quay.io/openshift/origin-console:latest"

# The upstream OLM repo that will be cloned and used for deployment
olm_repo: "https://github.com/operator-framework/operator-lifecycle-manager.git"
olm_repo_dest: /tmp/olm
olm_manifest_type: okd

# Template Broker and Ansible Brokers can be made available via the OLM
# catalog, creating an aditional catalog source and related OLM resources
olm_enable_osb_catalog: true
olm_osb_catalog_name: osb-operators

olm_osb_image_registry: docker.io
olm_osb_image_repo: automationbroker

olm_tsb_image_name: template-service-broker-operator
olm_tsb_image_tag: latest
olm_tsb_full_image: "{{ olm_osb_image_registry }}/{{ olm_osb_image_repo }}/{{ olm_tsb_image_name }}:{{ olm_tsb_image_tag }}"

olm_asb_image_name: automation-broker-operator
olm_asb_image_tag: latest
olm_asb_full_image: "{{ olm_osb_image_registry }}/{{ olm_osb_image_repo }}/{{ olm_asb_image_name }}:{{ olm_asb_image_tag }}"

# upstream: "Automation Broker", downstream: "Ansible Service Broker"
olm_asb_branding: upstream
